### ISSUE TITLE
Class Features not viewable upon update

### ISSUE THREAD

**Issue by kirito5445** [5etools-mirror-2/5etools-mirror-2.github.io#10]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: bug

Issue: Class Features/info not viewable upon update (v[1.206.0](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/releases), "Bodak Moment" Edition)

Page(s) affected: Classes. Other pages seem unaffected at this time.

Reproduction steps: Reload Classes page after the update, scroll down to see the features are no longer present.

Additional information: Disabled adblocker and antivirus software then reloaded page without change to the issue. 

Browser (Chromium, Firefox, Edge, etc): Chrome, Edge

Platform (Windows, iOS, Android, etc): Windows, Android

![Druid Capture](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/167935176/81bbfbd4-88f8-4063-bae2-c7dde4bd4e97)

**Comment by TheGiddyLimit** [comment]
works on my machine

![image](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/25264887/1d88f475-aeaf-4ca2-9565-6296d42fd783)

---

clear your cache/cookies; CTRL+F5; try it in an incognito window; etc. There's further troubleshooting advice in the [Discord](https://discord.gg/5etools), should you need it
