### ISSUE TITLE
Dark/Night mode broke

### ISSUE THREAD

**Issue by Carden-Gixoth** [5etools-mirror-2/5etools-mirror-2.github.io#11]
My dude, I don't know what you did during the update today, but it broke night mode. And the ALT. All pages. It's all disabled. The option to switch between Day, Night, and Night (Alt) is still there, but it does nothing. Mobile is fine, but PC is a flashbang

**Comment by TheGiddyLimit** [comment]
cannot reproduce; clear your cache/try an incognito window/another browser/use [the mirror](https://5etools-mirror-2.github.io/) etc

![image](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/25264887/ff821647-94b2-4227-a921-04dc2745916f)

![image](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/25264887/683ee08a-8d85-4236-96f8-e71775af4465)

![image](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/25264887/7e4a188e-13bc-41c3-b97d-f9c584bd00da)

![image](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/25264887/00f505ac-b8c0-46ca-84c1-80adb5c3bc60)
