### ISSUE TITLE
DM Screen Screen Initiative Tracker Darkmode still Light

### ISSUE THREAD

**Issue by BrysonVarner** [5etools-mirror-2/5etools-mirror-2.github.io#13]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
bug
Issue:
DM Screen initiative tracker shows up as light when dark mode active
Page(s) affected:
DM Screen
Reproduction steps:
DM layout W5 H4 embed location Row: 123 Col: 5 Dark mode
Additional information:

Browser (Chromium, Firefox, Edge, etc):
Chrome Browser
Platform (Windows, iOS, Android, etc):
Windows

**Comment by BrysonVarner** [comment]
My temporary solution is to change it in the inspector from #FFF to #000

**Comment by revilowaldow** [comment]
See https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/issues/11

**Comment by TheGiddyLimit** [comment]
cannot reproduce
