### ISSUE TITLE
Latest V11 version - importer fails on importing PHB feats

### ISSUE THREAD

**Issue by TheXeno30** [5etools-mirror-2/5etools-mirror-2.github.io#14]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: BUG

Issue: V11 importer fails on importing PHB feats

Page(s) affected: Feats

Reproduction steps: import feats from PHB

Additional information:
![image](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/135822719/441646f7-0646-44a5-86da-97f3c83c41a3)

Browser (Chromium, Firefox, Edge, etc): Chrome

Platform (Windows, iOS, Android, etc): Windows

**Comment by TheGiddyLimit** [comment]
fixed for next release
