### ISSUE TITLE
Homebrew Proficiency Bonus not change

### ISSUE THREAD

**Issue by Gus19** [5etools-mirror-2/5etools-mirror-2.github.io#20]
Hello !

Is this a bug or a feature request: Bug in display, calculs are fines

Issue: The Proficiency Bonus not change and the key is not in the json

Page(s) affected: https://5e.tools/makebrew.html#creaturebuilder

Reproduction steps: Change the field "Proficiency Bonus"
![image](https://github.com/user-attachments/assets/b100d648-0364-46e7-b533-a55c9b8538d7)

Browser : Firefox

Platform : Linux

**Comment by TheGiddyLimit** [comment]
yeah, the field below ("Proficiency Note"/`pbNote`) is what's actually used. The "Proficiency Bonus" there is just a helper for the builder. Swapped the order of the fields and improved the tooltips for next release
