### ISSUE TITLE
Images not loading after new update

### ISSUE THREAD

**Issue by sinha5432** [5etools-mirror-2/5etools-mirror-2.github.io#3]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Images aren't loading after new release

Page(s) affected: All of 5e.tools

Reproduction steps: Open 5e.tools in browser

Additional information: Tried with incognito mode as well as changed the browser

Browser (Chromium, Firefox, Edge, etc): Tried on Chromium (Brave) with ad blocker on/off, Tried on Edge as well

Platform (Windows, iOS, Android, etc): Windows

![image](https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/46960182/9e1354ef-0eed-46d6-8a2e-0fd335ee3d46)

**Comment by TheGiddyLimit** [comment]
please note: 5e.tools is not under the control of anyone involved in this repository

beyond that: well aware, and the relevant parties have been informed
