### ISSUE TITLE
Full-screen mode-non revertible

### ISSUE THREAD

**Issue by SpyrosMourelatos** [5etools-mirror-2/5etools-mirror-2.github.io#5]
Is this a bug or a feature request:
Small bug
Issue:
Non-revertible full screen mode in dm screen
Page(s) affected:
dm screen
Reproduction steps:
Just get in the full-screen mode in dm screen and try to get back to normal mode.
You will see that because sidemenu__toggle is left:-31 you can not revert!
Additional information:
I can fix it if you like, it is just removing a style from :
<img width="1396" alt="Screenshot 2024-03-08 at 14 00 48" src="https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/assets/26333139/7f20c4bc-2cac-45ca-a382-1fe614c1c092">
Or I can even try to make it less intrusive in full-screen mode
User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0

**Comment by revilowaldow** [comment]
It's just the display of the tab that's moved, if you move your mouse to the top left corner of the screen you'll have the panel appear again, including the full screen toggle to revert.

**Comment by TheGiddyLimit** [comment]
this is indeed working as intended, but admittedly isn't great

Will allow `ESC` to toggle it off for next release, and slightly tweak the menu button to have a few more pixels visible when it's "hidden"
